name: clip
description: .
version: 1.1.10
homepage: https://github.com/MoaidAlrazhy/dart-clip


environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  photo_view: ^0.14.0
  image_picker: ^1.0.7
  flutter_cache_manager: ^3.1.3
  flutter_native_image: ^0.0.6+1


dev_dependencies:
  test: ^1.5.1
